# Generated by Django 2.1.4 on 2019-01-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/profile.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
