# Generated by Django 2.1.5 on 2019-01-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_migrate_translatable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='_slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='_slug',
        ),
    ]
